name: UiPath CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: UiPath Pack
      uses: UiPath/pack@v2
      with:
        versionType: AutoVersion

    - name: UiPath Deploy
      uses: UiPath/deploy@v2
      with:
        orchestratorUrl: https://cloud.uipath.com/naren_wip/DefaultTenant
        tenantName: DefaultTenant
        accountName: naren_wip
        clientId: 2588a0b4-43ee-4e08-b0d8-c884a2a206c5
        clientSecret: y13Jv@EkTVYR$FGY6uB?0H#@q$ncGzHt^cWCZiWRtLOBr7NYpw^0n@LZ8l5rJTQF
        folderName: General